#!/usr/bin/env bash
# Cache-Control per path, served by the real nginx image with nginx.conf as its
# template — those headers decide whether a deploy reaches browsers through
# Cloudflare (see the comments in nginx.conf). Needs Docker.
#
#   anmates_flutter/tool/nginx_cache_test.sh
set -euo pipefail

conf=$(cd "$(dirname "$0")/.." && pwd)/nginx.conf
root=$(mktemp -d)
name=anmates-nginx-cache-test-$$
trap 'docker rm -f "$name" >/dev/null 2>&1 || true; rm -rf "$root"' EXIT

# A stand-in build/web: only the paths matter.
for f in index.html main.dart.js flutter_bootstrap.js favicon.png \
         assets/FontManifest.json assets/AssetManifest.bin assets/AssetManifest.bin.json \
         assets/fonts/MaterialIcons-Regular.otf \
         assets/packages/cupertino_icons/assets/CupertinoIcons.ttf \
         assets/assets/v2/hotpot.png; do
  mkdir -p "$root/$(dirname "$f")"
  echo x > "$root/$f"
done

# The upstream is an IP, so nothing needs resolving; /api/ is not exercised.
docker run -d --name "$name" -p 127.0.0.1::80 \
  -e API_UPSTREAM=http://127.0.0.1:9 -e NGINX_RESOLVER=127.0.0.11 \
  -v "$conf:/etc/nginx/templates/default.conf.template:ro" \
  -v "$root:/usr/share/nginx/html:ro" \
  nginx:1.27-alpine >/dev/null
port=$(docker port "$name" 80/tcp | head -1 | sed 's/.*://')
for _ in $(seq 50); do
  curl -fs -o /dev/null "http://127.0.0.1:$port/index.html" && break
  sleep 0.2
done

fail=0
expect() { # <path> <Cache-Control>
  local got
  got=$(curl -sI "http://127.0.0.1:$port$1" | tr -d '\r' | sed -n 's/^[Cc]ache-[Cc]ontrol: //p')
  if [ "$got" = "$2" ]; then
    echo "ok   $1  ($got)"
  else
    echo "FAIL $1  want '$2', got '$got'"
    fail=1
  fi
}

expect /index.html           'no-store, no-cache, must-revalidate'
expect /main.dart.js         'private, no-cache'
expect /flutter_bootstrap.js 'private, no-cache'
# Regenerated by every build under names that never change: the icon fonts
# are tree-shaken to the glyphs in use, the manifests list what exists.
expect /assets/fonts/MaterialIcons-Regular.otf                    'private, no-cache'
expect /assets/packages/cupertino_icons/assets/CupertinoIcons.ttf 'private, no-cache'
expect /assets/FontManifest.json                                  'private, no-cache'
expect /assets/AssetManifest.bin                                  'private, no-cache'
expect /assets/AssetManifest.bin.json                             'private, no-cache'
# Images keep the 2h cache.
expect /assets/assets/v2/hotpot.png 'public, max-age=7200'
expect /favicon.png                 'public, max-age=7200'

exit $fail
